export const SET_COURSE_STATUS = 'SET_STATUS';

export const CourseStatuses = {
  NOT_STARTED: 'NOT_STARTED',
  STARTED: 'STARTED',
  COMPLETED: 'COMPLETED',
};

export const MODULE_DONE = 'MODULE_DONE';

export const ASSESSMENT_DONE = 'ASSESSMENT_DONE';

export const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILURE: 'LOGIN_FAILURE',
};

export const LOGOUT = 'LOGOUT';
export const IMPORT_STATE = 'IMPORT_STATE';

export const REGISTER = {
  REQUEST: 'REGISTER_REQUEST',
  SUCCESS: 'REGISTER_SUCCESS',
  FAILURE: 'REGISTER_FAILURE',
};

export const GET_USER_DATA = {
  REQUEST: 'GET_USER_DATA_REQUEST',
  SUCCESS: 'GET_USER_DATA_SUCCESS',
  FAILURE: 'GET_USER_DATA_FAILURE',
};

export const CHOOSE_LANGUAGE = 'CHOOSE_LANGUAGE';

export const DOWNLOAD_RESOURCES = {
  REQUEST: 'DOWNLOAD_RESOURCES_REQUEST',
  SUCCESS: 'DOWNLOAD_RESOURCES_SUCCESS',
  FAILURE: 'DOWNLOAD_RESOURCES_FAILURE',
};

export const CHANGE_USER_DETAILS = 'CHANGE_USER_DETAILS';
export const CHANGE_LOGIN_PARAMS = 'CHANGE_LOGIN_PARAMS';

export const CHANGE_EMAIL = {
  REQUEST: 'CHANGE_EMAIL_REQUEST',
  SUCCESS: 'CHANGE_EMAIL_SUCCESS',
  FAILURE: 'CHANGE_EMAIL_FAILURE',
};

export const RESET_PASSWORD = {
  REQUEST: 'RESET_PASSWORD_REQUEST',
  SUCCESS: 'RESET_PASSWORD_SUCCESS',
  FAILURE: 'RESET_PASSWORD_FAILURE',
};

export const CANCEL_MESSAGES = 'CANCEL_MESSAGES';
